#!/usr/bin/env python
"""test_mp_build.py - auto-generated by softnanotools"""
from softnanotools.logger import Logger
logger = Logger(__name__)

if __name__ == '__main__':
    import doctest
    doctest.testmod()
