#!/usr/bin/env python
"""sun.py - auto-generated by softnanotools"""
import ray
import math
from typing import List
from softnanotools.logger import Logger
logger = Logger(__name__)

@ray.remote
def erf_mp(x):
    return math.erf(x)

def erf_futures(N: int) -> List[ray.ObjectRef]:
    futures = [erf_mp.remote(x) for x in range(N)]
    return futures

if __name__ == '__main__':
    import doctest
    doctest.testmod()
