# Builds using pip and tests using pytest

name: Windows Build

on:
  push:
    branches: [main, build*]
  pull_request:
    branches: [main, build*]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: windows-latest
        python-version: "3.11"
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Update Dependencies
      run: pip install --upgrade pip setuptools wheel softnanotools
    - name: Install
      run: pip install .
    - name: Test
      run: |
        pip install pytest
        pytest
